# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ERaftBooks
subtitle: ''
description: ''
keywords:
favicon: https://avatars.githubusercontent.com/u/84501959
author: John Doe
language:
  - zh-CN
  - en
  - zh-TW
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# url: https://eraft.cn
# permalink: :year/:month/:day/:title/
# permalink_defaults:
# pretty_urls:
#   trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
#   trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jekyll-theme-tactile

